# -*- coding: utf-8 -*-
"""task-3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LdgPz7aAUE51MATRlbhK3uN3KVhYVgVV

# 🌸 IRIS FLOWER CLASSIFICATION

## CodeVedX Internship – Task 3

### 📌 Project Objective
The objective of this project is to build a Machine Learning model that can classify Iris flowers into their respective species based on their sepal and petal measurements.

The Iris dataset contains measurements of three different Iris flower species:
- Setosa
- Versicolor
- Virginica

### 📂 Dataset
The dataset contains the following measurements:
- Sepal Length
- Sepal Width
- Petal Length
- Petal Width
- Species

### 🛠️ Technologies Used
- Python
- Pandas
- NumPy
- Matplotlib
- Seaborn
- Scikit-learn
- Google Colab

### 🔧 Data Preprocessing
The following preprocessing techniques will be used:
- Loading the dataset
- Checking missing values
- Checking duplicate records
- Selecting features and target
- Splitting the dataset into training and testing data

### 📊 Exploratory Data Analysis
The project will analyze:
- Distribution of Iris species
- Sepal measurements
- Petal measurements
- Relationships between flower measurements
- Pairwise relationships between features

### 🤖 Machine Learning Model
**Logistic Regression**

Logistic Regression will be used as the classification algorithm to classify Iris flowers into the three species.

### 📈 Model Evaluation
The model will be evaluated using:
- Accuracy Score
- Classification Report
- Confusion Matrix

### 🎯 Expected Outcome
The trained Machine Learning model should accurately classify an Iris flower into Setosa, Versicolor, or Virginica based on its sepal and petal measurements.
"""

# Import pandas for creating and handling data tables
import pandas as pd

# Import numpy for numerical calculations
import numpy as np

# Import matplotlib for creating graphs
import matplotlib.pyplot as plt

# Import seaborn for data visualization
import seaborn as sns

# Import the Iris dataset from Scikit-learn
from sklearn.datasets import load_iris

# Import function for splitting data into training and testing sets
from sklearn.model_selection import train_test_split

# Import Logistic Regression classification model
from sklearn.linear_model import LogisticRegression

# Import evaluation metrics
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Libraries imported successfully!")

# Load the Iris dataset from Scikit-learn
iris = load_iris()

# Create a DataFrame using the flower measurements
df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

# Add the target species number to the DataFrame
df["target"] = iris.target

# Add the actual species names
df["species"] = df["target"].map({
    0: "setosa",
    1: "versicolor",
    2: "virginica"
})

# Display the first 5 rows
df.head()

# Display the number of rows and columns
print("Dataset Shape:", df.shape)

# Display the column names
print("\nColumn Names:")
print(df.columns.tolist())

# Display information about the dataset
print("\nDataset Information:")
df.info()

# Check the number of missing values in each column
missing_values = df.isnull().sum()

# Display the missing values
print("Missing Values in Each Column:")
print(missing_values)

# Count duplicate rows
duplicate_count = df.duplicated().sum()

# Display the number of duplicate rows
print("Number of duplicate rows:", duplicate_count)

# Count the number of flowers in each species
print("Number of flowers in each species:")
print(df["species"].value_counts())

# Create a count plot
sns.countplot(data=df, x="species")

# Add title and labels
plt.title("Distribution of Iris Flower Species")
plt.xlabel("Species")
plt.ylabel("Number of Flowers")

# Display the graph
plt.show()

# Create a scatter plot of petal length and petal width
sns.scatterplot(
    data=df,
    x="petal length (cm)",
    y="petal width (cm)",
    hue="species"
)

# Add title
plt.title("Petal Length vs Petal Width")

# Display the graph
plt.show()

# Create pair plots to visualize relationships between flower measurements
sns.pairplot(
    df,
    hue="species"
)

# Display the graph
plt.show()

# Select the four flower measurements as input features
X = df[
    [
        "sepal length (cm)",
        "sepal width (cm)",
        "petal length (cm)",
        "petal width (cm)"
    ]
]

# Select the target variable
# 0 = Setosa
# 1 = Versicolor
# 2 = Virginica
y = df["target"]

# Display the first 5 feature rows
print("Features:")
display(X.head())

# Display the first 5 target values
print("\nTarget:")
print(y.head())

# Split the data into training and testing sets
# 80% will be used for training
# 20% will be used for testing

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

# Display the sizes of the datasets
print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

# Create the Logistic Regression model
model = LogisticRegression(max_iter=200)

# Train the model using the training data
model.fit(X_train, y_train)

print("Logistic Regression model trained successfully!")

# Use the trained model to predict the species of test flowers
y_pred = model.predict(X_test)

# Display the first 10 predictions
print("First 10 predicted classes:")
print(y_pred[:10])

# Calculate the percentage of correct predictions
accuracy = accuracy_score(y_test, y_pred)

# Display the accuracy
print("Model Accuracy:", round(accuracy * 100, 2), "%")

# Generate the classification report
# It contains precision, recall, F1-score, and support

print("Classification Report:")
print(
    classification_report(
        y_test,
        y_pred,
        target_names=iris.target_names
    )
)

# Calculate the confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Create a heatmap for the confusion matrix
sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    xticklabels=iris.target_names,
    yticklabels=iris.target_names
)

# Add title and labels
plt.title("Confusion Matrix - Iris Flower Classification")
plt.xlabel("Predicted Species")
plt.ylabel("Actual Species")

# Display the graph
plt.show()

# Create measurements for a new Iris flower
# Values represent:
# Sepal Length = 5.9 cm
# Sepal Width = 3.0 cm
# Petal Length = 5.1 cm
# Petal Width = 1.8 cm

new_flower = pd.DataFrame({
    "sepal length (cm)": [5.9],
    "sepal width (cm)": [3.0],
    "petal length (cm)": [5.1],
    "petal width (cm)": [1.8]
})

# Predict the species
prediction = model.predict(new_flower)

# Convert the predicted number into the species name
predicted_species = iris.target_names[prediction[0]]

# Display the prediction
print("Predicted Iris Species:", predicted_species)

# Display the final project summary

print("==========================================")
print("IRIS FLOWER CLASSIFICATION")
print("==========================================")

print("Machine Learning Algorithm: Logistic Regression")
print("Number of Training Samples:", len(X_train))
print("Number of Testing Samples:", len(X_test))
print("Model Accuracy:", round(accuracy * 100, 2), "%")
print("Predicted Sample Species:", predicted_species)

print("==========================================")
print("Project completed successfully!")
print("==========================================")
